"""Promotion artifact models and canonical identities."""

from e2h.promotion_evidence import (
    PairedEvaluationReport,
    PromotionCheck,
    PromotionError,
    PromotionEvidenceRole,
    PromotionGatePolicy,
    PromotionGateRule,
    PromotionProposal,
    StrictModel,
    VariantPrediction,
    VariantPredictionDocument,
    _ID_RE,
    _MAX_DOCUMENT_BYTES,
    _canonical_json_bytes,
)
from e2h.promotion_lifecycle import (
    PromotionDecision,
    PromotionDecisionKind,
    PromotionReceipt,
    RollbackEvent,
    RollbackOperator,
    RollbackPlan,
    RollbackTrigger,
    _exact_one_sided_mcnemar_tail,
    exact_one_sided_mcnemar_p_value,
    paired_evaluation_sha256,
    promotion_decision_sha256,
    promotion_policy_sha256,
    promotion_proposal_sha256,
    promotion_receipt_sha256,
    rollback_plan_sha256,
    variant_prediction_sha256,
)

__all__ = [
    "PairedEvaluationReport",
    "PromotionCheck",
    "PromotionDecision",
    "PromotionDecisionKind",
    "PromotionError",
    "PromotionEvidenceRole",
    "PromotionGatePolicy",
    "PromotionGateRule",
    "PromotionProposal",
    "PromotionReceipt",
    "RollbackEvent",
    "RollbackOperator",
    "RollbackPlan",
    "RollbackTrigger",
    "StrictModel",
    "VariantPrediction",
    "VariantPredictionDocument",
    "_ID_RE",
    "_MAX_DOCUMENT_BYTES",
    "_canonical_json_bytes",
    "_exact_one_sided_mcnemar_tail",
    "exact_one_sided_mcnemar_p_value",
    "paired_evaluation_sha256",
    "promotion_decision_sha256",
    "promotion_policy_sha256",
    "promotion_proposal_sha256",
    "promotion_receipt_sha256",
    "rollback_plan_sha256",
    "variant_prediction_sha256",
]
