name: Dependency review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Review dependency changes
        uses: actions/dependency-review-action@1e966ba708e4b64bb0c9bfb7abb5a232840be16a # post-v5.0.0 undici security update
        with:
          fail-on-severity: moderate
          fail-on-scopes: runtime, development, unknown
          show-patched-versions: true
